### ISSUE TITLE
Add some tags

### ISSUE THREAD

**Issue by nyalldawson** [icsm-au/icsm_qgis_transformer#5]
I'd suggest adding some extra tags to make this plugin more discoverable, e.g. "GDA2020", "GDA94", "EPSG:.... ", etc

**Comment by alexgleith** [comment]
I added a couple of tags here: https://github.com/icsm-au/icsm_qgis_transformer/commit/b63f023c2ca8494af247d01bc49e7becc462f6f3

I didn't want to add all the EPSG codes, as there's quite a lot of them.
